<?php 
$useIas = $this->getUseIas();
$useUitotop = $this->getUseScrollToTop();
if ($useIas) {
	// Get the default setting for grid or list mode
	$productListMode = $this->getDefaultCatalogListMode();
	if ($productListMode == 'grid-list')
		$productListMode = 'grid';
	elseif ($productListMode == 'list-grid')
		$productListMode = 'list';

	// Check if this setting is overwritten by the user
	if ($this->getCurrentListMode()) {
		if($this->getCurrentListMode() == 'grid')
			$productListMode = 'grid';
		else
			$productListMode = 'list';
	}
}
?>
<?php if ($useIas || $useUitotop): ?>
<script type="text/javascript">
<?php if ($useIas): ?>
jQuery.ias({
	container : '.category-products',
<?php if ($productListMode == 'grid'): ?>
	item: '.products-grid',
<?php else: ?>
	item: '.products-list',
	<?php endif; ?>
	pagination: '.toolbar .pager',
	next: '.next',
	loader: '<img src="<?php echo($this->getSkinUrl('images/ajaxscroll/loader.gif')); ?>" /> <?php echo __('Loading more products, please be patient...'); ?>',
<?php if($this->getGoogleAnalyticsEnabled()): ?>
	onPageChange: function(pageNum, pageUrl, scrollOffset) {
		// This will track a pageview every time the user scrolls up or down the screen to a different page.
		path = jQuery('<a/>').attr('href',pageUrl)[0].pathname.replace(/^[^\/]/,'/');
		_gaq.push(['_trackPageview', path]);
	},
<?php endif; ?>
	triggerPageThreshold: <?php echo $this->getIasTriggerpagethreshold(); ?>,
	thresholdMargin: <?php echo $this->getIasThresholdmargin(); ?>,
	trigger: '<?php echo __('Load more items'); ?>',
	history: <?php echo ($this->getIasHistory()) ? 'true' : 'false'; ?>
 });
<?php endif; ?>
<?php if ($useUitotop): ?>
jQuery(document).ready(function() {
	jQuery().UItoTop({ easingType: 'easeOutQuart' });		
});
<?php endif; ?>
</script>
<?php endif; ?>
